apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: default
spec:
  secretName: grafana-tls-secret # Debe coincidir con el secretName del Ingress
  dnsNames:
    - grafana.local.com
  #clusterIssuerRef se utiliza para referenciar un ClusterIssuer en lugar de un Issuer específico del namespace
  issuerRef:
    name: etsencrypt-http
    kind: ClusterIssuer
    group: cert-manager.io