apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-configmap
  namespace: default
data:
  prometheus-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: ${PROMETHEUS_URL} # La URL se sustituirá por la variable de entorno
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: http://loki-service:3100
        access: proxy
        isDefault: false