apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: default
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/grafana-data
    type: DirectoryOrCreate
