apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingressroute 
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`grafana.local`)
      services:
        - name: grafana-service
          # El puerto debe coincidir con el 'port' del Service de Grafana
          port: 80
          scheme: http
  tls:
    # indicamos a Traefik que use el secreto que 'cert-manager' ha creado.
    # El nombre debe coincidir con el 'secretName' del recurso Certificate.
    secretName: grafana-tls-secret