apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  otel-collector-config.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}

      filelog:
        include: ["/var/log/containers/*.log"]
        start_at: end

    processors:
      batch: {}
      attributes:
        actions:
          - key: cluster
            action: insert
            value: "local"

    exporters:
      loki:
        endpoint: "http://loki-service.default.svc.cluster.local:3100/loki/api/v1/push"
        labels:
          job: "otel-collector"

      logging:
        logLevel: debug

    service:
      pipelines:
        logs:
          receivers: [filelog, otlp]
          processors: [batch, attributes]
          exporters: [loki, debug]

        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
