apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
  namespace: otel
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
      filelog:
        include: ["/var/log/containers/*.log"]
        start_at: end

    processors:
      batch: {}
      attributes:
        actions:
          - key: cluster
            action: insert
            value: "local"
      memory_limiter:
        limit_mib: 1500
        spike_limit_mib: 512
        check_interval: 5s

    exporters:
      loki:
        endpoint: "http://loki.default.svc.cluster.local:3100/loki/api/v1/push"
        labels:
          job: "otel-collector"
      logging:
        logLevel: debug

    service:
      pipelines:
        logs:
          receivers: [filelog, otlp]
          processors: [batch, attributes]
          exporters: [loki, logging]

        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]